services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: mihneas22
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: flashdesk_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mihneas22 -d flashdesk_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
  api:
    build:
      context: ./backend/FlashDeskAPI
      dockerfile: Dockerfile
    depends_on:
      db: 
        condition: service_healthy
    env_file:
      - ./backend/FlashDeskAPI/FlashDeskAPI/keys.env
    ports:
      - "5000:8080"
    networks:
      - app-network

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontned/.env.local 
    ports:
      - "8080:3000"
    depends_on:
      - api
    networks:
      - app-network
  
  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe_cli
    depends_on:
      - api
    env_file:
      - ./backend/FlashDeskAPI/FlashDeskAPI/keys.env
    command: listen --forward-to http://api:8080/api/stripe/webhook
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  ocr-model-data:
