services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: mihneas22
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: flashdesk_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
  api:
    build:
      context: ./backend/FlashDeskAPI
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=flashdesk_db
      - DB_USER=mihneas22
      - DB_PASS=12345
    ports:
      - "5000:8080"
    networks:
      - app-network

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: