// <auto-generated />
using System;
using Infastructure.AppDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260502192146_user_stats_new")]
    partial class user_stats_new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Card", b =>
                {
                    b.Property<Guid>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Tips")
                        .HasColumnType("text[]");

                    b.Property<string>("ViewConfig")
                        .HasColumnType("jsonb")
                        .HasJsonPropertyName("viewConfig");

                    b.HasKey("CardId");

                    b.HasIndex("DeckId");

                    b.ToTable("CardEntity");
                });

            modelBuilder.Entity("Domain.Models.Deck", b =>
                {
                    b.Property<Guid>("DeckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeckUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.HasKey("DeckId");

                    b.HasIndex("DeckUserId");

                    b.ToTable("DeckEntity");
                });

            modelBuilder.Entity("Domain.Models.Streak", b =>
                {
                    b.Property<Guid>("StreakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("MaxStreak")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("StreakId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StreakEntity");
                });

            modelBuilder.Entity("Domain.Models.Test", b =>
                {
                    b.Property<Guid>("TestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Time")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.HasKey("TestId");

                    b.ToTable("TestEntity");
                });

            modelBuilder.Entity("Domain.Models.TestQuestion", b =>
                {
                    b.Property<Guid>("TestQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CorrectAnswerIndex")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<string[]>("Explications")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("Hints")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("PossibleAnswers")
                        .HasColumnType("text[]");

                    b.Property<Guid>("Quest_TestId")
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .HasColumnType("text");

                    b.HasKey("TestQuestionId");

                    b.HasIndex("Quest_TestId");

                    b.ToTable("TestQuestionEntity");
                });

            modelBuilder.Entity("Domain.Models.TestSubmission", b =>
                {
                    b.Property<Guid>("TestSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CorrectAnswers")
                        .HasColumnType("integer");

                    b.Property<int?>("Points")
                        .HasColumnType("integer");

                    b.Property<Guid>("Subm_TestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Subm_UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("WrongAnswers")
                        .HasColumnType("integer");

                    b.HasKey("TestSubmissionId");

                    b.HasIndex("Subm_TestId");

                    b.HasIndex("Subm_UserId");

                    b.ToTable("TestSubmissionEntity");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Elo")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("Roles")
                        .HasColumnType("text[]");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("UserEntity");
                });

            modelBuilder.Entity("Domain.Models.UserStats.CardReview", b =>
                {
                    b.Property<Guid>("CardReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rating")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TimeSpent")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("CardReviewId");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId");

                    b.ToTable("CardReview");
                });

            modelBuilder.Entity("Domain.Models.UserStats.DailyStats", b =>
                {
                    b.Property<Guid>("DailyStatsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("CardsMastered")
                        .HasColumnType("integer");

                    b.Property<int?>("CardsReview")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("MinSpent")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("DailyStatsId");

                    b.HasIndex("UserId");

                    b.ToTable("DailyStats");
                });

            modelBuilder.Entity("Domain.Models.UserStats.UserCardState", b =>
                {
                    b.Property<Guid>("UserCardStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid");

                    b.Property<float?>("EaseFactor")
                        .HasColumnType("real");

                    b.Property<float?>("IntervalDays")
                        .HasColumnType("real");

                    b.Property<string>("MasteryLevel")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("NextReview")
                        .HasColumnType("date");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("UserCardStateId");

                    b.HasIndex("CardId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCardState");
                });

            modelBuilder.Entity("Domain.Models.Card", b =>
                {
                    b.HasOne("Domain.Models.Deck", "CardDeck")
                        .WithMany("DeckCards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardDeck");
                });

            modelBuilder.Entity("Domain.Models.Deck", b =>
                {
                    b.HasOne("Domain.Models.User", "DeckUser")
                        .WithMany("UserDecks")
                        .HasForeignKey("DeckUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DeckUser");
                });

            modelBuilder.Entity("Domain.Models.Streak", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithOne("Streak")
                        .HasForeignKey("Domain.Models.Streak", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.TestQuestion", b =>
                {
                    b.HasOne("Domain.Models.Test", "Quest_Test")
                        .WithMany("Questions")
                        .HasForeignKey("Quest_TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quest_Test");
                });

            modelBuilder.Entity("Domain.Models.TestSubmission", b =>
                {
                    b.HasOne("Domain.Models.Test", "Subm_Test")
                        .WithMany("Submissions")
                        .HasForeignKey("Subm_TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "Subm_User")
                        .WithMany("UserSubmissions")
                        .HasForeignKey("Subm_UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subm_Test");

                    b.Navigation("Subm_User");
                });

            modelBuilder.Entity("Domain.Models.UserStats.CardReview", b =>
                {
                    b.HasOne("Domain.Models.Card", "Card")
                        .WithMany("CardReviews")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("UserCardReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.UserStats.DailyStats", b =>
                {
                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("UserDailyStats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.UserStats.UserCardState", b =>
                {
                    b.HasOne("Domain.Models.Card", "Card")
                        .WithMany("UserCardStates")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.User", "User")
                        .WithMany("UserCardStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Models.Card", b =>
                {
                    b.Navigation("CardReviews");

                    b.Navigation("UserCardStates");
                });

            modelBuilder.Entity("Domain.Models.Deck", b =>
                {
                    b.Navigation("DeckCards");
                });

            modelBuilder.Entity("Domain.Models.Test", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Domain.Models.User", b =>
                {
                    b.Navigation("Streak");

                    b.Navigation("UserCardReviews");

                    b.Navigation("UserCardStates");

                    b.Navigation("UserDailyStats");

                    b.Navigation("UserDecks");

                    b.Navigation("UserSubmissions");
                });
#pragma warning restore 612, 618
        }
    }
}
